In [45]:
# ---------- IMPORT ---------- #
import os
import pandas
from scipy.interpolate import CubicSpline
from sklearn.cluster import SpectralClustering
import numpy as np
from scipy.signal import periodogram
import matplotlib.pyplot as plt

In [46]:
# ----- CONSTANTS ----- #
in_dir = "datasets/features_post_avgM"
out_dir = ""
features = ["maxHR", "MaxRR", "StdHR", "lowFrequencyPower/highFrequencyPower", "%lowFrequencyPower", "VeryHighFrequenciesPower", "PNN50", "HighFrequenciesPower", "StdRR"]
subjectsToRemove = ["01", "02", "40"]

In [47]:
# ----- FUNCTIONS ----- #

In [48]:
# ----- MAIN ----- #
samples = []
for filename in os.listdir(in_dir):
    paziente = "{}".format(filename[1:3])
    if filename == "README.txt" or paziente in subjectsToRemove:
        continue
    featuresDF = pandas.read_csv("{}/{}".format(in_dir, filename), sep='\t', usecols = features ,low_memory=False)
    samples.append(featuresDF.mean(axis=0).to_list())
samples = np.array(samples)
for i in range(10):
    print("random state:{}".format(i))
    print("=====")
    for j in [0.1, 0.2, 0.5]:
        clustering = SpectralClustering(n_clusters=3, gamma=j, assign_labels="discretize", random_state=i).fit(samples)
        print("gamma={}:".format(j))
        print(clustering.labels_)
    print("=====")

random state:0
=====
gamma=0.1:
[1 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 2 0 1 0 0 1 2 1 1 0]
gamma=0.2:
[0 0 0 0 0 0 0 0 0 2 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 1 0 0 0]
gamma=0.5:
[1 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0]
=====
random state:1
=====
gamma=0.1:
[1 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 2 0 1 0 0 1 2 1 1 0]
gamma=0.2:
[2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0]
gamma=0.5:
[0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 2 0 0 0 0 1 2 0 0 0]
=====
random state:2
=====
gamma=0.1:
[0 2 0 0 0 2 2 0 2 0 2 0 0 2 2 0 2 2 2 0 2 0 2 0 2 2 2 1 2 0 2 2 0 1 0 0 2]
gamma=0.2:
[0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 0 1 1 1 2 1 1 1]
gamma=0.5:
[1 1 1 1 2 1 1 2 1 0 1 0 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 0 1 1 2 1 1 1 1]
=====
random state:3
=====
gamma=0.1:
[1 2 1 1 1 2 2 1 2 1 2 1 1 2 2 1 2 2 2 1 2 1 2 1 2 2 2 0 2 1 2 2 1 0 1 1 2]
gamma=0.2:
[2 1 1 1 1 1 1 1 